import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";
import Table from "../components/table";
import Form from "../components/form";
import { useDispatch, useSelector } from "react-redux";
import { setVisibleStatus } from "./store/stateSlice";

export default function Home() {
  const dispatch = useDispatch();
  const { visibleStatus: visible } = useSelector((state) => state.state);

  const handler = () => {
    dispatch(setVisibleStatus(!visible));
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5 px-4">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Customer Details
        </h1>

        <div className="container mx-auto flex justify-between py-5 px-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={()=>{handler()}}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Customer{" "}
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
        </div>

        {/* collapsable form */}
        {!visible ? <Form></Form> : <></>}

        {/* table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
